### ISSUE TITLE
ImportError: No module named en

### ISSUE THREAD

**Issue by SeekPoint** [vedic-partap/Event-Driven-Stock-Prediction-using-Deep-Learning#1]
ub16hp@UB16HP:~/ub16_prj/Event-Driven-Stock-Prediction-using-Deep-Learning$ python embeddingWord.py 
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "embeddingWord.py", line 8, in <module>
    import en
ImportError: No module named en

**Comment by kshivamraj32** [comment]
It does not affect in the updated code version
