### ISSUE TITLE
no news for any tickers

### ISSUE THREAD

**Issue by kshivamraj32** [vedic-partap/Event-Driven-Stock-Prediction-using-Deep-Learning#3]
The following line 48 in crawler_reuters might need an update-
"has_Content = len(soup.find_all("div", {'class': ['topStory', 'feature']}))"

fields 'topstory' & 'feature' do not exist on the page. Might need replacement with "MARKET VIEWS"

**Comment by toshal-a** [comment]
It's There on the page I cross checked It

**Comment by toshal-a** [comment]
![screenshot from 2018-12-08 23-14-04](https://user-images.githubusercontent.com/37237262/49688900-18a86280-fb3f-11e8-8312-78fcdbde4f59.png)
